#!/bin/sh

# Launcher script to work around limitations in vgmplay:
#   OSS only - detects oss wrapper and allows explicit selection
#   Config must be in working dir - automatically cd/mktemps as needed
#   Can't open release packs - plays from temporary directories

_force_output=
_pulse_server=      # Used when --pulse-server= is called
_log=
_log_path=
_pwd="$(pwd)"

_help () {
true
}

_to_stderr () {
    echo "$0: $2" 1>&2
    exit $1
}

_die () {
    case $1 in
        too_many_outputs )
            _to_stderr 64 "can only force one output type" ;;
		no_pulse_server )
			_to_stderr 64 "--pulse-server requires server parameter" ;;
        no_log_path )
            _to_stderr 64 "--log-to requires path parameter" ;;
        unknown_option )
            _to_stderr 64 "unrecognized option '$2'\nTry 'vgm-player --help' for more information."
    esac
}

_force_output () {
    if [ -n $_force_output ] && [ "$1" != "$_force_output" ]; then
		 _die too_many_outputs
	fi
    _force_output=$1

	case "$_force_output" in
		alsa )
			true ;;
	esac
}

_xdg_basedirs () {
	[ -z "$XDG_CONFIG_HOME" ] && XDG_CONFIG_HOME="$HOME/.config"
}

# Parse command line options
#   All single-letter options are exclusive
while :; do
    case $1 in
        --help )
            _help ;;
        --version )
            echo "VGMPlay 0.40.3 supporting VGM 1.70"
            exit 0 ;;
        -a | --alsa )
            _force_output alsa
			shift ;;
        -o | --oss )
            _force_output oss
			shift ;;
        -p | --pulse )
            _force_output pulse
			shift ;;
		-a* | -o* | -p* | -l* )
			_die too_many_outputs ;;
        --pulse-server=* )
            _force_output pulse
            _pulse_server="${1#*=}"
            [ -n "$_pulse_server" ] || _die no_pulse_server
            shift ;;
        -s* )
            _force_output pulse
            _pulse_server="${1#-s}"
            [ -n "$_pulse_server" ] || _die no_pulse_server
            shift ;;
        -s )
            _force_output pulse
            _pulse_server="$2"
            shift 2 ;;
        -l | --log )
			_force_output log
            _log_path="$_pwd"
            shift ;;
        --log-to=* )
            _force_output log
            _log_path="${1#*=}"
            [ -n "$_log_path" ] || _die no_log_path
            shift ;;
        --config=* )
			shift ;;
        --binary=* )
            shift ;;
        --override=* )
            shift ;;
        -* )
            _die unknown_option "$1" ;;
        -- )
            shift
            break ;;
        "" )
            _die no_music_file ;;
        * )
            break ;;
    esac
done

# Sanity checks:
#	Does `vgmplay` exist if --binary not specified?
#	Does the music file have a valid extension?
#	If a compressed pack, does a suitable unpacker exist?

